### ISSUE TITLE
New device documentation

### ISSUE THREAD

**Issue by bl4ckb0ne** [KhronosGroup/ANARI-SDK#167]
Is there documentation somewhere regarding implementing a new device ?

I'm working on a Vulkan device and I'm having a hard time grokking what should be in the `device.json` file, as well as setting up the skeleton of the device implementation.

I am working with C and don't intend to use `helium`.

Thanks.

**Comment by jeffamstutz** [comment]
Hi! This is definitely a gap in SDK documentation right now, so I'll do my best to direct you here.

Even though you're not planning on using `helium`, the `helide` device is still a reasonable reference point for some of the other miscellaneous things that device implementations need in order to work in the SDK:

- `ANARI_DEFINE_LIBRARY_ENTRYPOINT`  (Example [here](https://github.com/KhronosGroup/ANARI-SDK/blob/main/libs/helide/HelideLibrary.cpp#L42)) is what `anariLoadLibrary()` looks for when loading your library dynamically. You can probably just copy that file and change names to fit your library.
- The jsons are only used for generating device/object info data for `anariGetDeviceExtensions`, `anariGetObjectSubtypes`, `anariGetObjectInfo`, and `anariGetParameterInfo`. Those are about listing what extensions you implement that are in the core spec and then creating definitions for any extensions you add beyond the spec. The best strategy to use is to adapt an example json combined with CMake infrastructure for invoking the Python generation scripts (example [here](https://github.com/KhronosGroup/ANARI-SDK/blob/main/libs/helide/CMakeLists.txt#L50)).
- The main component you must implement is [DeviceImpl](https://github.com/KhronosGroup/ANARI-SDK/blob/main/libs/anari/include/anari/backend/DeviceImpl.h) -- yes it's a C++ pure-virtual class, but you don't have to use any C++ in order to use it. The stuff `helium` does is inject a class layer in between `DeviceImpl` and yours to handle generic stuff, but `DeviceImpl` itself is straight 1:1 with the public C API. If you understand the C API from the docs, then you should easily be able to implement `DeviceImpl` with whatever you want to do....it's ultimately up to you.

Let me know if you have any other questions, as there's plenty of things to talk about when starting a device from scratch!

**Comment by jeffamstutz** [comment]
FYI I just merged a README that explains the various aspects needed to get a device implementation going (viewable [here](https://github.com/KhronosGroup/ANARI-SDK/tree/next_release/libs/anari))....I hope that helps! Let me know if anything is unclear, thanks!

**Comment by bl4ckb0ne** [comment]
Thanks! I haven't had much time to sink into my anari device lately but I'll definetly go through that file.
