### ISSUE TITLE
Static builds + install target broken on Unix

### ISSUE THREAD

**Issue by szellmann** [KhronosGroup/ANARI-SDK#5]
When building the project statically and then installing to `CMAKE_INSTALL_PREFIX`, on Unix the anchoring logic that determines where to search for `libanari_device_XXX.so` will base the search path off the folder that the executables are located in (i.e., `bin`) and thus won't find the actual device library (which is installed to `lib`). Therefore, static builds currently only work when being used from the build tree.

**Comment by jeffamstutz** [comment]
Closing this as it is expected behavior -- the library anchoring search path checks the binary which the anchor is defined, where if it is static it will necessarily be the executable that linked `libanari.a`. Using `LD_LIBRARY_PATH` will still function, though, as well any RPATH injected by the linking executable.
